#!/bin/sh
# live-build configuration script
# see 'man lb config'

lb config noauto \
--apt-recommends false \
--apt-indices false \
--architectures amd64 \
--archive-areas 'main contrib non-free non-free-firmware' \
--backports true \
--security true \
--updates true \
--source false \
--binary-filesystem ext4 \
--binary-images iso-hybrid \
--checksums sha256 \
--clean \
--debconf-frontend noninteractive \
--debian-installer live \
--debian-installer-distribution bookworm \
--debian-installer-gui true \
--debootstrap-options "--include=apt-transport-https,ca-certificates,openssl" \
--distribution bookworm \
--firmware-binary true \
--firmware-chroot true \
--image-name bw-image \
--initramfs live-boot \
--iso-publisher brainworks \
--iso-volume debian-brainworks-1.1 \
--linux-packages "linux-image-liquorix linux-headers-liquorix" \
--bootappend-live "boot=live config splash" \
--memtest memtest86+ \
--win32-loader true

"${@}"
